# Generated by Django 2.1.1 on 2018-09-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishing_day',
            new_name='published_date',
        ),
    ]
